#!/bin/bash

clear

#initiate variables
c=1
a=0
order=(Pickup Delivery)
crust=(Thin NY_Style Sicilian)
options=(Pepperoni Ham Tomatoes Onions Jalapeno Cheese Red_Pepper Black_Olives)
drinks=(Coke Ice_tea Beer)
price=('$2' '$2.99' '$1')

#greeting customer

echo "     Welcome to Simply Delicious Pizza"
read -p "Please enter your name >> " name
echo ""
echo "Hello $name, We are happy to see you again :) "
echo ""
echo "Please enter you order below"
echo ""
sleep 1
# putting order types

echo "        Order Type "
echo "--------------------------------"
counter=1
for t in ${order[@]}
    do
        echo "$counter. $t"
        ((counter ++))
    done

#ask crust type
         read -p "Choose Order [1-2]" selections[$a]
    if [ ${selections[$a]} -gt 2 ]
          then
          read -p "Wrong order option, please choose again $c [1-2]" selections[$a]
  #else/for non intiger inputs
    #read -p "wrong order option, please choose again $c [1-2]" selections[$a]
    fi


#list summary order
echo ""
sleep 1
echo "You have selected order for ${order[${selections[0]}-1]}  "
sleep 1

# putting order types
echo ""
echo "Choose your crust"
sleep 1
echo "        Crust "
echo "--------------------------------"
counter=1
for t in ${crust[@]}
    do
       echo "$counter. $t"
       ((counter ++))
    done

#ask order type
         read -p "Choose Crust [1-3]" selections[$a]
         if [ ${selections[$a]} -gt 3 ]
          then
          read -p "Wrong order option, please choose again $c [1-3]" selections[$a]
         fi


#list summary order
sleep 1
echo ""
echo "You have selected ${crust[${selections[0]}-1]} crust for ${price[0]}, Great Choice! "
sleep 1
#give user a list of topping options
echo ""
echo "Choose your toppings, maximum of 4 toppings"
sleep 2
echo ""
echo '         Toppings'
echo "--------------------------------"
counter=1
for t in ${options[@]}
    do
        echo "$counter. $t"
        ((counter ++))
    done
sleep 2
#ask how many toppings they want
#read -p "How many toppings would you like? Enter 1-8 >> " nt

#while loop to ask topping question
echo ""
while [ $c -lt 5 ]
    do
            read -p "Topping $c [1-8]" selections[$a] 
        if [ ${selections[$a]} -gt 8 ] #ADD LESS THAN 1
            then
            read -p "Topping must be 1-8. Choose topping $c [1-8]" selections[$a]
        fi
           ((c++))
           ((a++)) 
    done
sleep 1
#listing summery of toppings
echo ""
echo -e "You have selected:
\n${options[${selections[0]}-1]} for ---- ${price[1]}
\n${options[${selections[1]}-1]} for ---------- ${price[1]}
\n${options[${selections[2]}-1]} for ----- ${price[1]} 
\n${options[${selections[3]}-1]} for ------- ${price[1]}

\nExcellent Choice!!! "
echo ""
echo "Would you like to order drink? [y / n]" 
read input
if [ $input == "y" ]; then  
    echo ""
    echo "Choose your Drink"
    sleep 1
    echo "        Drink "
    echo "--------------------------------"
    counter=1
    for t in ${drinks[@]}
        do
        echo "$counter. $t"
        ((counter ++))
        done

#ask order type
    read -p "Choose Drink [1-3]" selections[$a]
    if [ ${selections[$a]} -gt 3 ]
        then
        read -p "Wrong order option, Please choose again $c [1-3]" selections[$a]
    fi

#list summary order
    sleep 1
    echo ""
    echo "You have selected ${drinks[${selections[$a]}-1]}  for ${price[2]}"
    sleep 1
    echo "Excellent, $name! "
    echo ""
    sleep 1
    echo  -e "Your total is:
-------------------------------
    \nCrust ------------ ${price[0]}
    \n4-Topping -------- \$11.96
    \nDrinks ----------- ${price[2]}
    \nTax ------------- \$2.24
    \nSub Total ------- \$17.20 "
else
    sleep 1
        echo  -e "Excellent, $name!
Your total is:
-------------------------------
    \nCrust ------------ ${price[0]}
    \n4-Topping -------- \$11.96
    \nTax ------------- \$1.79
    \nSub Total ------- \$15.75 "

fi
echo ""
echo "Your order will be ready in 10 minutes."
echo ""
sleep 2
echo "Thank you for ordering from Simply Delicious Pizza."
echo""
echo "We hope you come visit us again soon!"

